// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class TestTest {

        private IWebDriver driver;
        public IDictionary<string, object> vars { get; private set; }
        private IJavaScriptExecutor js;
        private ChromeOptions options;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void test() {
    Thread.Sleep(1000);
    driver.Navigate().GoToUrl("https://localhost:44316/admin/login");
    Thread.Sleep(10000);
    driver.Manage().Window.Size = new System.Drawing.Size(1420, 620);
    driver.FindElement(By.Id("Email")).Click();
    driver.FindElement(By.Id("Email")).SendKeys("tieuanhtho@gmail.com");
    driver.FindElement(By.CssSelector(".h-100")).Click();
    driver.FindElement(By.Id("AdminPassword")).Click();
    driver.FindElement(By.Id("AdminPassword")).SendKeys("test");
    driver.FindElement(By.CssSelector(".btn")).Click();
    driver.FindElement(By.CssSelector(".bi-clipboard")).Click();
    driver.FindElement(By.CssSelector(".even:nth-child(2) .btn-danger")).Click();
    driver.FindElement(By.CssSelector("#delete2 .btn-danger")).Click();
    Thread.Sleep(50000);
    driver.Close();
  }
}
