// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class ViewUserStatitisTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void viewUserStatitis() {
    driver.Navigate().GoToUrl("https://localhost:44316/admin/login");
    driver.Manage().Window.Size = new System.Drawing.Size(1420, 620);
    driver.FindElement(By.Id("Email")).Click();
    driver.FindElement(By.Id("Email")).SendKeys("tieuanhtho@gmail.com");
    driver.FindElement(By.CssSelector(".h-100")).Click();
    driver.FindElement(By.Id("AdminPassword")).Click();
    driver.FindElement(By.Id("AdminPassword")).SendKeys("test");
    driver.FindElement(By.Id("AdminPassword")).SendKeys(Keys.Enter);
    driver.FindElement(By.CssSelector(".body-column:nth-child(1) .mat-card-title")).Click();
    Assert.That(driver.FindElement(By.CssSelector(".body-column:nth-child(1) .mat-card-title")).Text, Is.EqualTo("Visitors"));
    driver.FindElement(By.CssSelector(".body-column:nth-child(2) .mat-card-title")).Click();
    Assert.That(driver.FindElement(By.CssSelector(".body-column:nth-child(2) .mat-card-title")).Text, Is.EqualTo("New accounts"));
  }
}
