// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
namespace DuoLegendTesting.Tests.SeleniumTests
{
    [TestFixture]
    public class TestChatBox
    {
        private IWebDriver driver;
        public IDictionary<string, object> vars { get; private set; }
        private IJavaScriptExecutor js;
        [SetUp]
        public void SetUp()
        {
            driver = new ChromeDriver();
            js = (IJavaScriptExecutor)driver;
            vars = new Dictionary<string, object>();
        }
        [TearDown]
        protected void TearDown()
        {
            driver.Quit();
        }
        [Test]
        public void testChatBox()
        {
            driver.Navigate().GoToUrl("https://localhost:5001/");
            driver.Manage().Window.Size = new System.Drawing.Size(1936, 1056);
            driver.FindElement(By.LinkText("Login")).Click();
            driver.FindElement(By.Id("email")).Click();
            driver.FindElement(By.Id("email")).SendKeys("duykhang28@gmail.com");
            driver.FindElement(By.CssSelector("body")).Click();
            driver.FindElement(By.Id("id_password")).Click();
            driver.FindElement(By.Id("id_password")).SendKeys("12345678");
            driver.FindElement(By.CssSelector(".button")).Click();
            Thread.Sleep(5000);
            driver.FindElement(By.LinkText("NnY")).Click();
            driver.FindElement(By.Id("openChatButton")).Click();
            Thread.Sleep(5000);
            driver.FindElement(By.Id("messageInput")).Click();
            driver.FindElement(By.Id("messageInput")).SendKeys("test");
            driver.FindElement(By.CssSelector(".bi-arrow-left-circle-fill")).Click();
            {
                var element = driver.FindElement(By.CssSelector(".bi-arrow-left-circle-fill"));
                Actions builder = new Actions(driver);
                builder.MoveToElement(element).Perform();
            }
            {
                var element = driver.FindElement(By.TagName("body"));
                Actions builder = new Actions(driver);
                builder.MoveToElement(element, 0, 0).Perform();
            }
            Thread.Sleep(5000);
            driver.FindElement(By.CssSelector(".message:nth-child(5)")).Click();
            Assert.That(driver.FindElement(By.CssSelector(".message:nth-child(5)")).Text, Is.EqualTo("test"));
        }
    }
}
